### ISSUE TITLE
Update Version

### ISSUE THREAD

**Issue by mhakim168** [setrem/time-tracking-osTicket#2]
is there any update for v1.14 or is this compatible with v1.14?

**Comment by setrem** [comment]
Hello, @mhakim168. We have not updated our version yet. Therefore, the changes have not been tested in version v1.14. However, looking at version v1.14, the changes we made seem compatible. I think it is worth trying in a development environment.

**Comment by setrem** [comment]
Hello, @mhakim168. The plugin was tested on osTicket v1.14.2 and works well.
